### ISSUE TITLE
デバッグ

### ISSUE THREAD

**Issue by karayuumac** [karayuumac/Gigantic#23]
全体的にデバッグが不十分、特に前プラグインのMEBIUSからの引継ぎ
簡単なデバッグは行っているが、引継ぎは一切デバッグ出来ていない。
引継ぎのデバッグが不十分な場合、取り返しがつかなくなる可能性あり。

**Comment by karayuumac** [comment]
Clickしただけで経験値が増えていくバグ？が見つかった。
また、スキルが発動できない(重力値の制限等)際でも経験値が増えていく。

**Comment by karayuumac** [comment]
[20:31:11 INFO]: _karapu_ issued server command: /growth name といれ
[20:31:11 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'growth' in plugin Gigantic v0.1.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-de459a2-51263e9]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-de459a2-51263e9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: No enum constant com.github.unchama.growthtool.GrowthTool.GrowthToolType.NAME
        at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_131]
        at com.github.unchama.growthtool.GrowthTool$GrowthToolType.valueOf(GrowthTool.java:92) ~[?:?]
        at com.github.unchama.command.commands.GrowthCommand.onCommand(GrowthCommand.java:100) ~[?:?]
        at com.github.unchama.gigantic.Gigantic.onCommand(Gigantic.java:133) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-de459a2-51263e9]
        ... 15 more

**Comment by karayuumac** [comment]
解決。プルリク済み。終了。
